ci: add pre-commint linting and extract major-minor

diff --git a/.github/workflows/docs.yaml b/.github/workflows/docs.yaml
--- a/.github/workflows/docs.yaml
+++ b/.github/workflows/docs.yaml
@@ -18,35 +18,35 @@ defaults:
     working-directory: ./docs
 
 jobs:
-  # FIXME: shouldn't lint on all all files, ooof, needs to be in the PRs only
-  # FIXME: some of the rules need tweaking
-  # lint:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v4
+  lint:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
 
-  #     - uses: pdm-project/setup-pdm@v3
-  #       with:
-  #         python-version: '3.11'
-  #         cache: true
-  #         cache-dependency-path: docs/pdm.lock
+      - uses: pdm-project/setup-pdm@v3
+        with:
+          python-version: '3.11'
+          cache: true
+          cache-dependency-path: docs/pdm.lock
 
-  #     - name: install
-  #       run: pdm install
+      - name: install
+        run: pdm install
 
-  #     - uses: pre-commit/action@v3.0.0
-  #       with:
-  #         extra_args: markdownlint --all-files --verbose
-  #       env:
-  #         SKIP: no-commit-to-branch
+      - uses: pre-commit/action@v3.0.0
+        with:
+          extra_args: markdownlint --verbose
+        env:
+          SKIP: no-commit-to-branch
 
   publish:
-    # needs: [lint]
+    needs: [lint]
     runs-on: ubuntu-latest
     timeout-minutes: 30
     env:
       CONTRIBUTORS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       DOCS_BRANCH: gh-pages
+      DOCS_LATEST_ALIAS: latest
+      DOCS_DEVELOPMENT_ALIAS: dev
     steps:
       - name: checkout docs-site
         uses: actions/checkout@v4
@@ -66,16 +66,27 @@ jobs:
           pdm venv create --with-pip --force $PYTHON
           pdm install
 
-      - name: Set git credentials
+      - name: set git credentials
         run: |
           git config --global user.name "${{ github.actor }}"
           git config --global user.email "${{ github.actor }}@users.noreply.github.com"
 
-      - run: pdm run mike deploy -b ${{ env.DOCS_BRANCH }} dev --push
-        # FIXME: Something like this
-        # if: "github.ref == 'refs/heads/main'"
-        if: "github.ref == 'refs/heads/feat/initial-documentation'"
+      - name: get major-minor tag for docs
+        if: "startsWith(github.ref, 'refs/tags/')"
+        id: tag
+        run: |
+          MINOR=$(echo "${{ github.ref_name }}" | sed -En 's/^v?(([0-9]+)\.([0-9]+))\.([0-9]+)$/\1/p')
+          [ "$MINOR" != "" ] || { echo "Couldn't parse tag to get major-minor version"; exit 1; }
+          echo "minor=$MINOR" >> $GITHUB_OUTPUT
 
-      # FIXME: fetch the current version by either listening to release-please or by listening to tag events
-      - run: pdm run mike deploy -b ${{ env.DOCS_BRANCH }} 4.4 latest --update-aliases --push
-        if: "(github.ref == 'refs/heads/feat/initial-documentation' || startsWith(github.ref, 'refs/tags/'))"
+      - name: deploy latest development documentation
+        run: >-
+          pdm run mike deploy -b "${{ env.DOCS_BRANCH }}"
+          "${{ env.DOCS_DEVELOPMENT_ALIAS }}" --push
+        if: "github.ref == 'refs/heads/main'"
+
+      - name: deploy latest documentation for v${{ steps.version.outputs.tag }}
+        run: >-
+          pdm run mike deploy -b "${{ env.DOCS_BRANCH }}"
+          "${{ steps.tag.outputs.minor }}" "${{ env.DOCS_LATEST_ALIAS }}" --update-aliases --push
+        if: "startsWith(github.ref, 'refs/tags/')"
